//
// Created by lord on 05.12.2022.
//

#ifndef EXERCICE_73_NOMBRES_RATIONNELS_BASE_RATIONNEL_H
#define EXERCICE_73_NOMBRES_RATIONNELS_BASE_RATIONNEL_H
class Rationnel{

};
#endif //EXERCICE_73_NOMBRES_RATIONNELS_BASE_RATIONNEL_H
